// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAqJh6iZYf27VvhdvwlNZxRN0Idrm3vaM',
    appId: '1:144662156270:web:1f13a5d135888ba4e774ff',
    messagingSenderId: '144662156270',
    projectId: 'buy-nest-5187a',
    authDomain: 'buy-nest-5187a.firebaseapp.com',
    storageBucket: 'buy-nest-5187a.firebasestorage.app',
    measurementId: 'G-621GPHYDX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHXYh8IDFZni1ov79z46KMG0PbQKN3018',
    appId: '1:144662156270:android:c65c544ace0dfb2fe774ff',
    messagingSenderId: '144662156270',
    projectId: 'buy-nest-5187a',
    storageBucket: 'buy-nest-5187a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiPQcbUSXJeEOlZrgsL8sHroXxVvl0uDQ',
    appId: '1:144662156270:ios:b2d29eb01d14610fe774ff',
    messagingSenderId: '144662156270',
    projectId: 'buy-nest-5187a',
    storageBucket: 'buy-nest-5187a.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceShoppingStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiPQcbUSXJeEOlZrgsL8sHroXxVvl0uDQ',
    appId: '1:144662156270:ios:b2d29eb01d14610fe774ff',
    messagingSenderId: '144662156270',
    projectId: 'buy-nest-5187a',
    storageBucket: 'buy-nest-5187a.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceShoppingStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAqJh6iZYf27VvhdvwlNZxRN0Idrm3vaM',
    appId: '1:144662156270:web:2256af480e2ebb40e774ff',
    messagingSenderId: '144662156270',
    projectId: 'buy-nest-5187a',
    authDomain: 'buy-nest-5187a.firebaseapp.com',
    storageBucket: 'buy-nest-5187a.firebasestorage.app',
    measurementId: 'G-H000LBNCPX',
  );
}
